services:
  - type: web
    name: safedate-mcp
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python mcp-bearer-token/mcp_starter.py
    autoDeploy: true
    envVars:
      - key: AUTH_TOKEN
        sync: false
      - key: MY_NUMBER
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GIPHY_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
